### ISSUE TITLE
Contributing solutions to r4ds exercises

### ISSUE THREAD

**Issue by rdotsch** [rfordatascience/rfordatasciencewiki#1]
Hi guys,

As mentioned [here](https://twitter.com/RonDotsch/status/906923564997148673), I have some answer keys to many r4ds exercises from a course I taught last year. I am happy to contribute those here. Currently, they are in .Rmd format, with one file for each week of the 8 week course. If you set up an initial commit, I can then create a pull request to add my contributions.

Best,

Ron

**Comment by ellisvalentiner** [comment]
@rdotsch I've pushed an initial commit.

Thanks for helping out with this!

**Comment by rdotsch** [comment]
I opened a PR (#2) to push my solutions. As noted in the PR, you may want to refactor and decide on some folder structure. I just put them in the root folder now. Enjoy!
